apiVersion: v1
kind: ServiceAccount
metadata:
  name: lambda-sa
  namespace: devsarena
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lambda-role
  namespace: devsarena
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "services"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lambda-rolebinding
  namespace: devsarena
subjects:
- kind: ServiceAccount
  name: lambda-sa
roleRef:
  kind: Role
  name: lambda-role
  apiGroup: rbac.authorization.k8s.io